### PR TITLE
Refactoring database for user uids

### PR DESCRIPTION
**Pull request by rkuenzi-epfl**
- [x]  Give uniques ids to signed in user (using firebase sign in)
- [x]  Store users infos and their guesses under their uid
- [x]  Optionnaly update the picture database to have coherent guess entry with users

I already changed the way we sign in. We now get a google token and send it to firebase to authenticate with it. And signed in users now have uid that we will use to get their respective data instead of user names.
However changing the way we store guesses will take a lot more time because it means we have to refactor both the user and picture database classes to take into account the uid.

### CODE REVIEW

**Comment by rkuenzi-epfl** [comment]
Test are not updated yet but please start reviewing.

**Review by BoostedBoat — CHANGES_REQUESTED** [review]
I'm actually pretty impressed at how it's well written. I hope I haven't missed anything important though.
However the coverage is really low and it really impacts the global coverage, is it only because of the sign in part ? Or is there a good reason for this ?

**Comment by BoostedBoat** [comment]
Also, once it's merged, don't forget to tell everyone what has changed in the db

**Comment by BoostedBoat** [comment]
Also, I wasn't able to tell where it comes from but there's a bug in the scoreboard: the current user is displayed at top in another color to differentiate him from the others, however its place is not written anymore.
image

**Comment by rkuenzi-epfl** [comment]
> Also, I wasn't able to tell where it comes from but there's a bug in the scoreboard: the current user is displayed at top in another color to differentiate him from the others, however its place is not written anymore.

Yes with the new way we get scoreboard (in particular the current user score) we can't really get the position in the scoreboard, as we did berfore it was wrong anyway (you would get someone else's score if you both had the same display name) and putting it back properly required way to much effort.

**Comment by rkuenzi-epfl** [comment]
We won't have time to complete this properly so I'm closing the PR.

**Pull request closed without merging**
