### PR TITLE
Bugfix: GPS should not crash in case we don't have the right permissions

### PR DESCRIPTION
**Pull request by leonardvaney**
What will be done in this PR:

- [x] If the user wants to deny the permission to access his GPS, the application should not crash right away.
- [x] When the user wants to access a feature that is not accessible without the GPS, we should not let him access it and tell him why.

### CODE REVIEW

**Review by BoostedBoat — CHANGES_REQUESTED** [review]
The fix works when you open the app without the location activated/if you refuse to give the permission. However, if you deactivate the service while using the app/once you've already given the permission, it still crashes (don't know if it's very clear).

**Comment by leonardvaney** [comment]
> 
> 
> The fix works when you open the app without the location activated/if you refuse to give the permission. However, if you deactivate the service while using the app/once you've already given the permission, it still crashes (don't know if it's very clear).

I have changed the way it is handled. Now if either the GPS or the permission are not available when we want to acces the position, it should launch the NavigationActivity and warn the user.

**Review by rkuenzi-epfl — APPROVED** [review]
Everything works on my side, maybe you should also send the users back to the main activity when they can't access a fragment because they denied GPS access just because the empty fragments look bad. And in that case you could rerequest GPS access maybe?
It fixes the bug anyway so the rest is only small improvements.

**Comment by BoostedBoat** [comment]
> The fix works when you open the app without the location activated/if you refuse to give the permission. However, if you deactivate the service while using the app/once you've already given the permission, it still crashes (don't know if it's very clear).

Doesn't work by my side, but apparently it's a local issue so I'll delete my changes request and let another person approve

**Review by JeremyDezalos — APPROVED** [review]
Everything works on my emulator. Maybe FYI @BoostedBoat I used the API level 30

**Pull request merged**
