### PR TITLE
BUGFIX: can't guess "no photos available" anymore

### PR DESCRIPTION
**Pull request by BoostedBoat**
Guessing  inexistant photos (and making the app crash) is now no longer possible. (Guess button will only show if the picture is legit and guessable)

### CODE REVIEW

**Comment by BoostedBoat** [comment]
Sorry for the name of the branch, I got a bit confused

**Review by amattei777 — APPROVED** [review]
FGTM

**Review by leonardvaney — APPROVED** [review]
I liked that bug...

**Comment by BoostedBoat** [comment]
> I liked that bug...

too sad

**Pull request merged**
